### ISSUE TITLE
Blank page running release example in README on Ubuntu 20.04

### ISSUE THREAD

**Issue by mt206** [marcomq/nimview#11]
Hi. Following the instructions on compiling a release build runs successfully.
`nim c -d:release --app:gui src/App.nim `
 When I actually run the program `./src/App.nim` it is just a blank screen. 
![image](https://user-images.githubusercontent.com/3315522/124348197-66719400-db9d-11eb-97c1-519304e74f85.png)

When I use dev mode (`nim c -r -d:debug src/App.nim`) though it runs fine launched from the browser. 

Is it possible there is an issue with inlined.html or possibly something else? Note that this is the Svelte project in `examples/`

**Comment by mt206** [comment]
Seems to be an issue with the Svelte example specifically. I ran the Vue example and that worked, although I got some errors in the app during startup before the ui loaded in:
`getGlobalToken failed` and `getRequests failed` in `dist/index.html` with the Vue app. 
![image](https://user-images.githubusercontent.com/3315522/124348950-aa669800-dba1-11eb-9ed1-76a74b1d929b.png)

**Comment by marcomq** [comment]
Hi! Thx for trying out. 
This actually is the kind of feedback I was hoping for. I'm not always able to test the latest code on an actual GUI on each platform. I usually just use the Http mode on WSL for testing linux, as it doens't require starting up a VM.
It seems that gtk on linux has some issues with the generated javascript. Didn't expect this, as previous code only had issues with IE on windows.
I'm not able to replicate a complete white page, but I can replicate those errors - and that the svelte and vue examples are not doing what they should do. I hope I can fix those errors soon - maybe on Monday. Maybe earlier if this is something simple. Will keep you up to date.

**Comment by marcomq** [comment]
So - I wasn't really able to replicate the blank screen, but I was able to identify a major timeout issue on the nimview.js npm package which had the result that some js wasn't loaded correctly when running with gtk on linux. 
I made a fix and the svelte example is working again in release mode on my VM with Centos 8 and Nim 1.4.8.
Already pushed the change to git and published a new nimview package on npm.

I will just close this issue now.
Please add some feedback if this isn't solving your issue.

**Comment by mt206** [comment]
Awesome. Thanks for the quick reply and quick resolution. I will check out the new version. I think this is a great project.
