### ISSUE TITLE
Make windows frameless

### ISSUE THREAD

**Issue by Cr3atable** [marcomq/nimview#12]
Being able to build my own window controls and disable native ones is a big part of any GUI framework I end up using, but I did not see a way in Nimview to make a window frameless.

**Comment by marcomq** [comment]
Hi!
There are some limitations, as nimview uses webview as library to render everything. And the nim webview version also doesn't seem to be the latesr one, so there might also be some features missing that are available in the latest version.

There is already an issue in webview repo for this:
https://github.com/webview/webview/issues/97

**Comment by marcomq** [comment]
I just added some borderless mode for linux
`setBorderless`
Didn't had time yet to test it yet. but it is implemented according to the documentation and it also seems to compile in the automated tests
