### ISSUE TITLE
Css problem

### ISSUE THREAD

**Issue by C-NERD** [marcomq/nimview#13]
Hi I just cross compiled nimview for windows and the UI component on windows lack the css styling i applied to it. Some portion of the css seems to work like 'cursor : pointer' but other than that nothing else works. Please is there a way to overcome this.

**Comment by marcomq** [comment]
Hi!
There could be multiple things that avoid that the css is applied correctly:
- the css file path is absolute. It needs to be relative
- the css library (when used) isn't compatible to IE 11 
-  ...
You can check in the debug / Http Server mode with IE11 first if this is related to path or IE11 by pressing F11. There, you can check if the file was loaded etc...

**Comment by C-NERD** [comment]
Thanks I'll have a look at the iE11 documentation and debug mode to see what I did wrong. Also it's non of the example it's a project i am working on

**Comment by marcomq** [comment]
If you post some minimal example that is replicating your issue, I can maybe try if I can resolve it.
There currently isn't that much documentation, and I never actually tried to cross-compile it.

**Comment by marcomq** [comment]
I changed some code for GTK. Maybe this solves your issue. If not, please post some minimal example, so I can try to replicate it.

**Comment by C-NERD** [comment]
Sorry for not responding, i just saw an email notification of your message. About the code i switched the graphics library for the project so i really can't provide a sample(because i cleared it) for you but the code compiles and work the way it's meant to(tested on linux) the only problem i have is when I cross compiled the code into a .exe file, then the WebView instance seem to have some problems rendering my css. Thanks again for taking your time to respond i really appreciate it🙇🏽‍♂️

**Comment by C-NERD** [comment]
> I changed some code for GTK. Maybe this solves your issue. If not, please post some minimal example, so I can try to replicate it.

And i don't think the problem is with GTK, because if i remember from reading the documentation windows uses a different rendering engine. It probably that the application could not load the css file because i remember using css in html and it seems to work(can't really remember memory a little foggy but something like this)

**Comment by marcomq** [comment]
Hm... Ok. I still didn't try to cross compile nimview. Maybe this is related to webview.

Some workaround may be to use an inliner to inline all css into html, as inline css works. Most examples - svelte, vue, svelte-todo already do this when running "npm run build".
