### ISSUE TITLE
Backend not working in Webview

### ISSUE THREAD

**Issue by konradmb** [marcomq/nimview#15]
Steps to reproduce:

1. Run minimal example (`examples/minimal/`): `nim c -r -d:release --app:gui App.nim`
2. Click "click" button
3. Nothing happens, but alert should open

With debug turned on (last line of App.nim changed to `startDesktop("dist/index.html", debug=true)`) this shows up in console:
```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.external.invoke')
	dispatchException (nimview.iife.js:1:27644)
	(anonymous function) (nimview.iife.js:1:23878)
	t (nimview.iife.js:1)
	s (nimview.iife.js:1:321)
	promiseReactionJob

[Error] TypeError: window.backend.echoAndModify is not a function. (In 'window.backend.echoAndModify(document.getElementById('sampleInput').value)', 'window.backend.echoAndModify' is undefined)
	onclick (index.html:13)
```

**Comment by marcomq** [comment]
Thx for reporting this issue.

On which OS does this issue happen?
Which nim version are you using?

**Comment by konradmb** [comment]
Ubuntu 21.04

```
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 44e653a9314e1b8503f0fa4a8a34c3380b26fff3
active boot switches: -d:release
```

```
Package: libwebkit2gtk-4.0-dev
Version: 2.32.3-0ubuntu0.21.04.1
```

**Comment by konradmb** [comment]
Oh, and nimview from master

**Comment by marcomq** [comment]
Thx. I will try to replicate it.
On my windows machine, everything works fine. So this might be related to some compatibility issue with GTK... Maybe there is some data url escaping issue.
Unfortunately, this might take some time, maybe even some days.

**Comment by marcomq** [comment]
Just some status update:
I was able to replicate the issue on Ubuntu. The major issue is that "window.external.invoke" seems to be undefined in Javascript, when trying to call the webview callback function. There also was some similar issue for an old version of webview https://github.com/webview/webview/issues/236
Unfortunately, waiting for the content to be loaded doesn't seem to solve the issue. The issue seens to happen for all registered "backend" functions. It currently looks like it isn't possible to just trigger some basic webview functionality.
I will try to find some solution in the next days. Still no idea how this can be fixed, but I will work on this.

**Comment by konradmb** [comment]
Looks like Nim Webview wrapper is severely outdated, and since the Webkit library is newer and shipped by system, the code doesn't match newer API in Webkit.
I'm trying to update https://github.com/oskca/webview but the codebase changed so much, that the wrapper needs to be rewritten probably.

**Comment by marcomq** [comment]
Yes - the webview library hasn't been updated for some time.
The concept and architecture changed for windows with the latest webview version.
The new version doesn't seem to be able to create static binaries anymore, as the webview library always seem to require a dll.
Updating it is still a good idea, as IE is deprecated and it also seem to create issues on new linux versions (Centos 8 still works)

**Comment by marcomq** [comment]
Status update:
It seems that this issue doesn't appear in the latest webview version, so updating/upgrading webview seems to be the best option. Unfortunately, updating might be a lot of work. There are some basic PRs, for example https://github.com/oskca/webview/pull/17, but those aren't tested and they don't even include the "bind" command, which would be required for nimview. And it also isn't even the latest version of webview.

Good news is that I found some way to create static executables for windows with the latest version of webview https://github.com/webview/webview/issues/600 
Not having single executable files with any compiler would have been a real blocker for me. I only tested using msvc as compiler, but this actually is also my preferred cpp compiler on windows. And gcc/clang might probably still be possible using a dll (if it doesn't work out of the box). 

So, I will probably fork the current nim webview and have some new webview library instead. Not sure when I will have time for this, but I will post some early repository link here as soon as I start.

**Comment by konradmb** [comment]
I've successfully generated a new wrapper with nimterop. I will post it in a repo later. First, I need to check out if it even works. :sweat_smile:

**Comment by marcomq** [comment]
Not sure if you were able to create some running version with nimterop. I guess the main Problem is the linker, as Webview has changed to c++ and creates trouble when trying to link with Nim. 
I made some fork here: 
https://github.com/marcomq/webview
It is very basic and I was just able to start some minimal example with vcc on windows. I guess it will still create major issues on linux or on mac. It is still a lot of work. I'm not sure if I should really try to create static binaries or if I should try to use some dynamic linked dll version. The old Webview was much easier to handle.

**Comment by konradmb** [comment]
Check this out: https://github.com/konradmb/webview/tree/update
It needs a cleanup, but more or less, the API is done. Of course it's not working just like this with nimview, because there are a couple of changes in underlying C++ library. 
A quick summary:
- bindProc lost it's scope argument, so you would need to check what needs to be changed in JS nimview
- setColor, info alert etc. are removed, so you would need to consider using GTK, but I think this feature was mostly unused
- C++ only - as you said. I'm using C wrappers, but even the code inside C functions uses C++, so it needs to be compiled with g++

Try running `nim r --backend:cpp src/wrapper.nim` and use some functions in JS console. It works!
If you need this scope feature, I can try reworking it, but from what I've tried, it would need a couple of hacks, like waiting for page load, so it would be better to just use some prefix like "nimview_" in function name.

Just tell me what you like (or not) :smiley:

**Comment by marcomq** [comment]
Wow. Looks good! Even more complete than I thought.

**Comment by marcomq** [comment]
Hey - so I had some deeper look at the branch and I'm not sure if nimterop really is a simplification here. There seem to be multiple different compile and linker options, depending on the OS that is used. And it seems to be complicate to pass those to nimterop.
I'm glad that it seems to run on linux, but I have some trouble compiling it on windows. This is probably because I'm completely new to nimterop and also because I'm still quite new to nim yet.

Also, I'm not sure if we should really always pull the latest webview version. By this, the nim code will probably break if webview makes some breaking change. Maybe it makes sense to use the current latest hash "f540d88" and update / test it from time to time.

Still great that you were able to get it running that quickly on linux! I think this is great good start for a new webview update.

**Comment by konradmb** [comment]
Yeah, I need to dust off my Windows install and see what needs to be done. Overally, I think that nimterop is harder to setup, but it would be more stable with any future changes. As a last resort I can generate wrapper once and commit it to repo (but I hope that wouldn't be required).

I will freeze webview to exact hash with submodule. That's the way I think would be the best to do.

Also, I want to have the same setup as you on Windows, did you downloaded it from https://nim-lang.org/install_windows.html ?

**Comment by marcomq** [comment]
I think I used choosenim to install nim.
Will have a deeper look at nimterop. Not sure when I have time for it but it is on my Todo list :)

**Comment by marcomq** [comment]
I got some first compiling version for windows:
https://github.com/francisl/webview/compare/main...marcomq:windows?expand=1
But I still need to make some changes for vcc. I want a binary for windows that doesn't need these dll files. Currently, header.nim is still using gcc with dll files.
I changed some code parts in the header.nim - not sure if everything was correct. As I said - I'm still new to nimterop :) You can ignore my changes if you think that they don't make sense or if there is some better solution.

**Comment by marcomq** [comment]
Sry - I created my branch above on the wrong base. I created a new one on your base.
I was able to compile a static binary on windows with --cc:vcc and on ubuntu using the test/minimal.nim example `nim cpp -r tests/minimal.nim`.
Unfortunately, using nimterop didn't work on windows with vcc. So I just used the function signature output of the run and copied it to header.nim. 
Status:
Using "bindProcs" doesn't work yet. And this needs some additional cleanup for windows, as there are issues converting from const char* to char* 

Just wanted to check if this would still be ok for you. if we just copy the output of nimterop manually. I renamed "bind" and "return" to "bindCb" and "returnCb", so I didn't need to use quotes. I made some minor changes in wrapper.nim but most of the code in wrapper.nim wasn't touched yet.
https://github.com/konradmb/webview/compare/update...marcomq:update?expand=1

**Comment by marcomq** [comment]
Thx. I will try to work on this the next days. 
I think I found something that might have caused the issue in webkit2gtk > 2.31: https://github.com/marcomq/webview/blob/master/webview.nim#L223
(not verified yet)
Maybe I will add some compile switch to be able to switch to new and an old webview.

**Comment by marcomq** [comment]
Some good news:
I got the demo running on Ubuntu 21.04
I made following changes:
- fixed webview.nim to define window.external.invoke on gtk
- added webview locally as subtree, so I the PR doesn't need to be merged to the original webview library
- updated to the latest C99 webview of go wails
- changed the way data urls are generated, in case that "inlined.html" is used as url, so that gtk can handle it
- updated js so that data urls can be detected on gtk (you need to update nimview when used in npm packages.json
- added some additional experimental compile time flag "-d:webview" so that webview2 can be used (can compile, has probably a lot of issues)

**Comment by konradmb** [comment]
Yay, thanks!
