### ISSUE TITLE
full screen mode in nim view

### ISSUE THREAD

**Issue by kalbhairab** [marcomq/nimview#16]
is there any support for full screen mode in nim view

**Comment by marcomq** [comment]
I never tried the full screen mode, but there is a function for it from webview:
https://htmlpreview.github.io/?https://github.com/marcomq/nimview/blob/master/docs/nimview.html#setFullscreen%2Cbool
You need to perform 
```
start(run=false)
setFullscreen(true)
run()
```

**Comment by kalbhairab** [comment]
if we can make app fullscreen then it may behave as a gui language for nim.

**Comment by marcomq** [comment]
I was already thinking about switching to the latest webview version. But the latest webview doesn't has a fullscreen mode anymore. I guess I will keep still the old webview for some time, so we can also keep the fullscreen mode.

**Comment by marcomq** [comment]
So - I just tested the fullscreen mode and it works fine on windows. You might still need to add some shortcut or button to shutdown the application. This then should trigger "stop()" in nim. Otherwise, the Application can only be stopped with [alt] + [F4]

Here was the "svelte" sample code:

``` 
import nimview

proc appendSomething(value: string): string {.noSideEffect.} =
  result = "'" & value & "' modified by svelte sample"

proc main() =
  addRequest("appendSomething", appendSomething)
  start(run=false)
  setFullscreen(true)
  run()
  # startHttpServer()
  
when isMainModule:
  main()
  ```
