### ISSUE TITLE
publish apk to playstore.

### ISSUE THREAD

**Issue by kalbhairab** [marcomq/nimview#17]
sir plz publish your apk to playstore.

**Comment by marcomq** [comment]
Hey! Do you mean that I should create a apk from examples/android and publish this to playstore? I actually haven't published anything to the playstore yet, but this sounds like a good idea.
Do you have a good and quick tutorial? Otherwise, I will just google some.

**Comment by kalbhairab** [comment]
I am new to programming in nim but if you use nim to make apk of todo and publish the sample to play store with the tutorial then it will be very helpful. I like to help in your work but i am new, but i like to work with your idea if you help me.

**Comment by kalbhairab** [comment]
If you cant publish apk then make apk and share from google drive

**Comment by marcomq** [comment]
So, I found the registration form to upload and sign an App. https://play.google.com/console/signup
The registration fee is currently 25$, which isn't much, but still to much to spend it without proper reason :)
Maybe I will register as soon as I have some really good Android App and not just a simple ToDo App.

So - here is an apk of the demo app, I found at "android/app/build/outputs/apk/debug/app-debug.apk", packaged as zip as gh has issues with .apk files.
Not sure if you can use it. Usually, Android doesn't install apk files anymore, if they aren't signed. So, it is better to install Android Studio (with Android NDK) and build it yourself.
[app-debug.zip](https://github.com/marcomq/nimview/files/7077406/app-debug.zip)

**Comment by kalbhairab** [comment]
can it build karax app

**Comment by marcomq** [comment]
> can it build karax app

In theory - yes. It can also use plain vanilla javascript. There is an example for it in exampes/minimal. I haven't tried yet.
However, you would need to use something like babel to make it compatible to IE11, if you are on windows. I haven't used babel with karax.

**Comment by kalbhairab** [comment]
Sir Plz make apk available in demo zip folder.

**Comment by marcomq** [comment]
> Sir Plz make apk available in demo zip folder.

I have no idea how to deploy the apk to an android phones without using android studio.

I wouldn't publish anything where I would have no idea how to actially use it.
