### ISSUE TITLE
Building in release mode does not seem to work

### ISSUE THREAD

**Issue by trisub** [marcomq/nimview#24]
I'm on Nim 1.4.8, Linux and I'm trying to a build a simple example in release mode. I have a Nim file (copied verbatim from readme):

```nim
import nimview
nimview.addRequest("echoAndModify", proc (value: string): string =
  echo "From front-end: " & value
  result = "'" & value & "' modified by back-end")
nimview.start()
```

I also have `dist/index.html` and `dist/inlined.html` both of which contain the string "Hello World". Building in dev mode works fine, I can open localhost:8000 and see "Hello World".

If I do `nim c -d:release --app:gui src/minimal.nim` and run the binary, a window opens but it displays `SGVsbG8gV29ybGQhCg==` which base64 decodes to "Hello World". So it seems like there is missing a decoding step for the inlined.html.

**Comment by marcomq** [comment]
Thx for reporting. I can confirm that there is an issue. 
No idea why I didn't see it during testing but will create a fix for it soon. Just need to start my Linux VM and test it there :)

**Comment by marcomq** [comment]
I just created a fix on the current `main` branch.  I will probably create a new Tag soon.
I wasn't actually able to replicate the issue on Centos8, but I could see in the code that the base64 data-url modifier was missing. So I just added it and it keeps working on Centos8. I hope that it still works on your Linux distribution.

Let me know if it works / if it doesn't work.

**Comment by trisub** [comment]
I just tested it and I can build now the minimal example as well as the Svelte todo app for release without problems. Thanks for the quick response!

**Comment by marcomq** [comment]
Thx for the feedback. Will create a new fix tag soon.
