### ISSUE TITLE
Compiling with "just_core" flag - Error redefinition of "compileWithWebview" const

### ISSUE THREAD

**Issue by georgelemon** [marcomq/nimview#31]
```
nimview.nim(109, 9) Error: redefinition of 'compileWithWebview';
previous declaration here: nimview-0.3.3/nimview.nim(13, 7)
```

**Comment by marcomq** [comment]
Thx!
Thought I had a test case for this...
Will check!

**Comment by marcomq** [comment]
So - I added some additional test cases that also test if an application also compiles with "just_core" and fixed the code accordingly. Just pushed it to the main branch.

I also had some functions renamed - but nim code should still work with the old function names.
Will soon add a new tag for version v0.4
