### ISSUE TITLE
Build error on react example

### ISSUE THREAD

**Issue by gavr123456789** [marcomq/nimview#35]
```
> yarn build
yarn run v1.22.17
$ react-scripts build && inliner -m --videos --preserve-comments dist/index.html > dist/inlined.html
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'jquery/dist/jquery.js' in '/home/gavr/nimView/nimview/examples/react/src'


error Command failed with exit code 1
```  
And there really is no jquery, and why would it be here?  
And also `nim c -r -d:debug src/App.nim` failed, because it cant find file index in /dist/index.html  
As I undestand - npm build creating that.

**Comment by marcomq** [comment]
> And there really is no jquery, and why would it be here?

For bootstrap css, as in any other example. Bootstrap has some effects which rely on jQuery.

I never tried "yarn", so this might be related to "yarn". 
I just added jQuery to the package.json and run "npm run build". Looks good.

**Comment by gavr123456789** [comment]
nice, now it works(with yarn too).  How to run dev build now? There is no dev script like in others examples.

**Comment by marcomq** [comment]
Right... I didn't modify the default react package.json yet. 
I guess you can use `npm start` for development and `npm run build` for release. I think there was no auto-refresh yet for react.
