### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mantielero** [marcomq/nimview#9]
I am trying to intall in ArchLinux `nimble install nimview` and I also tried directly from github.

I get the following  error:
```
  Verifying dependencies for nake@1.9.4
 Installing nimview@0.1.2
   Building nimview/nimview using c backend
/home/jose/.nimble/pkgs/jester-#head/jester.nim(704, 26) Error: undeclared identifier: 'initInterval'
candidates (edit distance, scope distance); see '--spellSuggest':
```

My nim is v1.5.1.

**Comment by mantielero** [comment]
My bad. The installation of jester wasn't ok. Fixed by removing: `~/.nimble/pkgs/jester-#head`

**Comment by marcomq** [comment]
Np :) Thx for trying it out. 
I'm currently re-writing parts of it and already removed the jester dependencies in my develop branch. Will merge it as soon as I fixed some bugs...
